apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: cpuscale
spec:
  containers:
  - name: cpu-demo-ctr
    image: k8s.gcr.io/hpa-example
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
