apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helloworld-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    app: HelloWorld
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 1
