apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helloworld-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: learnkubeone-54d75bbc7c
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 1
