apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helloworld-scaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: learnkubeone
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 30
