apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helloworld-scaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: learnkubeone
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 30
