apiVersion: apps/v1
kind: Deployment
metadata:
  name: serveronetestdeploy
  labels:
    app: servertestone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servertestone
  template:
    metadata:
      labels:
        app: servertestone
    spec:
      containers:
      - name: serveronecontainer
        image: lokeshkoppaka/cloudcomputing.spring2019:firstImage 
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        ports:
        - containerPort: 81
