apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverthreetestdeploy
  labels:
    app: servertestthree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servertestthree
  template:
    metadata:
      labels:
        app: servertestthree
    spec:
      containers:
      - name: serverthreecontainer
        image: lokeshkoppaka/cloudcomputing.spring2019:thirdImage 
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        ports:
        - containerPort: 80
